/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MasiniRouteImport } from './routes/masini'
import { Route as DespreNoiRouteImport } from './routes/despre-noi'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasiniIndexRouteImport } from './routes/masini.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MasiniSlugRouteImport } from './routes/masini.$slug'
import { Route as ImgSplatRouteImport } from './routes/img.$'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as AdminSetariRouteImport } from './routes/admin.setari'
import { Route as AdminMasiniRouteImport } from './routes/admin.masini'
import { Route as AdminLeaduriRouteImport } from './routes/admin.leaduri'
import { Route as AdminDespreRouteImport } from './routes/admin.despre'
import { Route as AdminMasiniIndexRouteImport } from './routes/admin.masini.index'
import { Route as AdminMasiniNouRouteImport } from './routes/admin.masini.nou'
import { Route as AdminMasiniIdEditRouteImport } from './routes/admin.masini.$id.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MasiniRoute = MasiniRouteImport.update({
  id: '/masini',
  path: '/masini',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreNoiRoute = DespreNoiRouteImport.update({
  id: '/despre-noi',
  path: '/despre-noi',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasiniIndexRoute = MasiniIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MasiniRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MasiniSlugRoute = MasiniSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MasiniRoute,
} as any)
const ImgSplatRoute = ImgSplatRouteImport.update({
  id: '/img/$',
  path: '/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetariRoute = AdminSetariRouteImport.update({
  id: '/setari',
  path: '/setari',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMasiniRoute = AdminMasiniRouteImport.update({
  id: '/masini',
  path: '/masini',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaduriRoute = AdminLeaduriRouteImport.update({
  id: '/leaduri',
  path: '/leaduri',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDespreRoute = AdminDespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMasiniIndexRoute = AdminMasiniIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMasiniRoute,
} as any)
const AdminMasiniNouRoute = AdminMasiniNouRouteImport.update({
  id: '/nou',
  path: '/nou',
  getParentRoute: () => AdminMasiniRoute,
} as any)
const AdminMasiniIdEditRoute = AdminMasiniIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminMasiniRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/masini': typeof MasiniRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/despre': typeof AdminDespreRoute
  '/admin/leaduri': typeof AdminLeaduriRoute
  '/admin/masini': typeof AdminMasiniRouteWithChildren
  '/admin/setari': typeof AdminSetariRoute
  '/api/upload': typeof ApiUploadRoute
  '/img/$': typeof ImgSplatRoute
  '/masini/$slug': typeof MasiniSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/masini/': typeof MasiniIndexRoute
  '/admin/masini/nou': typeof AdminMasiniNouRoute
  '/admin/masini/': typeof AdminMasiniIndexRoute
  '/admin/masini/$id/edit': typeof AdminMasiniIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/despre': typeof AdminDespreRoute
  '/admin/leaduri': typeof AdminLeaduriRoute
  '/admin/setari': typeof AdminSetariRoute
  '/api/upload': typeof ApiUploadRoute
  '/img/$': typeof ImgSplatRoute
  '/masini/$slug': typeof MasiniSlugRoute
  '/admin': typeof AdminIndexRoute
  '/masini': typeof MasiniIndexRoute
  '/admin/masini/nou': typeof AdminMasiniNouRoute
  '/admin/masini': typeof AdminMasiniIndexRoute
  '/admin/masini/$id/edit': typeof AdminMasiniIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/masini': typeof MasiniRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/despre': typeof AdminDespreRoute
  '/admin/leaduri': typeof AdminLeaduriRoute
  '/admin/masini': typeof AdminMasiniRouteWithChildren
  '/admin/setari': typeof AdminSetariRoute
  '/api/upload': typeof ApiUploadRoute
  '/img/$': typeof ImgSplatRoute
  '/masini/$slug': typeof MasiniSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/masini/': typeof MasiniIndexRoute
  '/admin/masini/nou': typeof AdminMasiniNouRoute
  '/admin/masini/': typeof AdminMasiniIndexRoute
  '/admin/masini/$id/edit': typeof AdminMasiniIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/despre-noi'
    | '/masini'
    | '/sitemap.xml'
    | '/admin/despre'
    | '/admin/leaduri'
    | '/admin/masini'
    | '/admin/setari'
    | '/api/upload'
    | '/img/$'
    | '/masini/$slug'
    | '/admin/'
    | '/masini/'
    | '/admin/masini/nou'
    | '/admin/masini/'
    | '/admin/masini/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/despre-noi'
    | '/sitemap.xml'
    | '/admin/despre'
    | '/admin/leaduri'
    | '/admin/setari'
    | '/api/upload'
    | '/img/$'
    | '/masini/$slug'
    | '/admin'
    | '/masini'
    | '/admin/masini/nou'
    | '/admin/masini'
    | '/admin/masini/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/despre-noi'
    | '/masini'
    | '/sitemap.xml'
    | '/admin/despre'
    | '/admin/leaduri'
    | '/admin/masini'
    | '/admin/setari'
    | '/api/upload'
    | '/img/$'
    | '/masini/$slug'
    | '/admin/'
    | '/masini/'
    | '/admin/masini/nou'
    | '/admin/masini/'
    | '/admin/masini/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DespreNoiRoute: typeof DespreNoiRoute
  MasiniRoute: typeof MasiniRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ImgSplatRoute: typeof ImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masini': {
      id: '/masini'
      path: '/masini'
      fullPath: '/masini'
      preLoaderRoute: typeof MasiniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre-noi': {
      id: '/despre-noi'
      path: '/despre-noi'
      fullPath: '/despre-noi'
      preLoaderRoute: typeof DespreNoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masini/': {
      id: '/masini/'
      path: '/'
      fullPath: '/masini/'
      preLoaderRoute: typeof MasiniIndexRouteImport
      parentRoute: typeof MasiniRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/masini/$slug': {
      id: '/masini/$slug'
      path: '/$slug'
      fullPath: '/masini/$slug'
      preLoaderRoute: typeof MasiniSlugRouteImport
      parentRoute: typeof MasiniRoute
    }
    '/img/$': {
      id: '/img/$'
      path: '/img/$'
      fullPath: '/img/$'
      preLoaderRoute: typeof ImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setari': {
      id: '/admin/setari'
      path: '/setari'
      fullPath: '/admin/setari'
      preLoaderRoute: typeof AdminSetariRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/masini': {
      id: '/admin/masini'
      path: '/masini'
      fullPath: '/admin/masini'
      preLoaderRoute: typeof AdminMasiniRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaduri': {
      id: '/admin/leaduri'
      path: '/leaduri'
      fullPath: '/admin/leaduri'
      preLoaderRoute: typeof AdminLeaduriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/despre': {
      id: '/admin/despre'
      path: '/despre'
      fullPath: '/admin/despre'
      preLoaderRoute: typeof AdminDespreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/masini/': {
      id: '/admin/masini/'
      path: '/'
      fullPath: '/admin/masini/'
      preLoaderRoute: typeof AdminMasiniIndexRouteImport
      parentRoute: typeof AdminMasiniRoute
    }
    '/admin/masini/nou': {
      id: '/admin/masini/nou'
      path: '/nou'
      fullPath: '/admin/masini/nou'
      preLoaderRoute: typeof AdminMasiniNouRouteImport
      parentRoute: typeof AdminMasiniRoute
    }
    '/admin/masini/$id/edit': {
      id: '/admin/masini/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/masini/$id/edit'
      preLoaderRoute: typeof AdminMasiniIdEditRouteImport
      parentRoute: typeof AdminMasiniRoute
    }
  }
}

interface AdminMasiniRouteChildren {
  AdminMasiniNouRoute: typeof AdminMasiniNouRoute
  AdminMasiniIndexRoute: typeof AdminMasiniIndexRoute
  AdminMasiniIdEditRoute: typeof AdminMasiniIdEditRoute
}

const AdminMasiniRouteChildren: AdminMasiniRouteChildren = {
  AdminMasiniNouRoute: AdminMasiniNouRoute,
  AdminMasiniIndexRoute: AdminMasiniIndexRoute,
  AdminMasiniIdEditRoute: AdminMasiniIdEditRoute,
}

const AdminMasiniRouteWithChildren = AdminMasiniRoute._addFileChildren(
  AdminMasiniRouteChildren,
)

interface AdminRouteChildren {
  AdminDespreRoute: typeof AdminDespreRoute
  AdminLeaduriRoute: typeof AdminLeaduriRoute
  AdminMasiniRoute: typeof AdminMasiniRouteWithChildren
  AdminSetariRoute: typeof AdminSetariRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDespreRoute: AdminDespreRoute,
  AdminLeaduriRoute: AdminLeaduriRoute,
  AdminMasiniRoute: AdminMasiniRouteWithChildren,
  AdminSetariRoute: AdminSetariRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MasiniRouteChildren {
  MasiniSlugRoute: typeof MasiniSlugRoute
  MasiniIndexRoute: typeof MasiniIndexRoute
}

const MasiniRouteChildren: MasiniRouteChildren = {
  MasiniSlugRoute: MasiniSlugRoute,
  MasiniIndexRoute: MasiniIndexRoute,
}

const MasiniRouteWithChildren =
  MasiniRoute._addFileChildren(MasiniRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DespreNoiRoute: DespreNoiRoute,
  MasiniRoute: MasiniRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiUploadRoute: ApiUploadRoute,
  ImgSplatRoute: ImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
